version: "3.9"
services:
  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql
    env_file:
      - ./.env/.zabbix-postgres-env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 172.10.10.2

  redis:
    image: redis
    restart: always
    env_file:
      - ./.env/.zabbix-redis-env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      network:
        ipv4_address: 172.10.10.3

  server:
    image: zabbix/zabbix-server-pgsql:6.4.6-ubuntu
    env_file:
      - ./.env/.zabbix-server-env
    healthcheck:
      test: grep -qr "zabbix_server" /proc/*/status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - postgres
      - redis
    networks:
      network:
        ipv4_address: 172.10.10.4


  dashboard:
    image: zabbix/zabbix-web-nginx-pgsql:6.4.6-ubuntu
    env_file:
      - ./.env/.zabbix-dashboard-env
    ports:
      - 10000:8080
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - postgres
      - redis
    networks:
      network:
        ipv4_address: 172.10.10.5

#  zabbix-agent:
#    image: zabbix/zabbix-agent2:6.4.6-ubuntu
#    environment:
#      ZBX_HOSTNAME: zabbix-server
#      ZBX_SERVER_HOST: zabbix-server
#      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
#    restart: unless-stopped
#    depends_on:
#      - zabbix-postgres
#      - zabbix-server
#      - zabbix-redis
#    links:
#      - zabbix-postgres
#      - zabbix-server
#      - zabbix-redis
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/29
      options:
        com.docker.network.bridge.enable_ip_masquerade: "true"

volumes:
  postgres:
