version: "3.9"
services:
  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql
    env_file:
      - .env
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_DB=zabbix
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      network:

  redis:
    image: redis
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      network:

  server:
    image: zabbix/zabbix-server-pgsql:6.4.6-ubuntu
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=zabbix
      - POSTGRES_DB=zabbix
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - DB_SERVER_HOST=postgres
      - ZABBIX_REMOTECOMMANDS=1
    healthcheck:
      test: grep -qr "Zabbix server" /proc/*/status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - postgres
      - redis
    networks:
      network:

  dashboard:
    image: zabbix/zabbix-web-nginx-pgsql:6.4.6-ubuntu
    env_file:
      - .env
    environment:
    - ZBX_SERVER_NAME=server
    - ZBX_SERVER_HOST=server
    - ZBX_SERVER_PORT=10051
    - DB_SERVER_HOST=postgres
    - DB_SERVER_PORT=5432
    - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=zabbix
    - POSTGRES_DB=zabbix
    ports:
      - 10000:8080
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - postgres
      - redis
    networks:
      network:

#  zabbix-agent:
#    image: zabbix/zabbix-agent2:6.4.6-ubuntu
#    environment:
#      ZBX_HOSTNAME: zabbix-server
#      ZBX_SERVER_HOST: zabbix-server
#      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
#    restart: unless-stopped
#    depends_on:
#      - zabbix-postgres
#      - zabbix-server
#      - zabbix-redis
#    links:
#      - zabbix-postgres
#      - zabbix-server
#      - zabbix-redis
networks:
  network:

volumes:
  postgres:
