version: "3.9"
services:
  db:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      zabbix-network:
        ipv4_address: 172.80.80.5

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      zabbix-network:
        ipv4_address: 172.80.80.4

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.4.6-ubuntu
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - DB_SERVER_HOST=db
      - ZABBIX_REMOTECOMMANDS=1
    env_file:
      - .env
    healthcheck:
      test: grep -qr "zabbix_server" /proc/*/status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - db
      - redis
    networks:
      zabbix-network:
        ipv4_address: 172.80.80.2


  zabbix-dashboard:
    image: zabbix/zabbix-web-nginx-pgsql:6.4.6-ubuntu
    environment:
      ZBX_SERVER_NAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      DB_SERVER_HOST: db
      DB_SERVER_PORT: 5432
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - 10000:8080
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - db
      - redis
    networks:
      zabbix-network:
        ipv4_address: 172.80.80.3

#  zabbix-agent:
#    image: zabbix/zabbix-agent2:6.4.6-ubuntu
#    environment:
#      ZBX_HOSTNAME: zabbix-server
#      ZBX_SERVER_HOST: zabbix-server
#      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
#    restart: unless-stopped
#    depends_on:
#      - db
#      - zabbix-server
#      - redis
#    links:
#      - db
#      - zabbix-server
#      - redis
networks:
  zabbix-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.80.80.0/24
      options:
        com.docker.network.bridge.enable_ip_masquerade: "true"

volumes:
  db
