version: '2.3'

services:
  redis:
    restart: always
    image: redis:6.2.6
    command:
    - --loglevel warning
    volumes:
    - redis-data:/data:Z
    networks:
      network:

  postgres:
    restart: always
    image: postgres:14
    volumes:
    - postgres:/var/lib/postgresql:Z
    environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=gitlab
    networks:
      network:

  app:
    restart: always
    image: gitlab/gitlab-ce:16.7.3-ce.0
    depends_on:
    - redis
    - postgres
    ports:
    - "80:80"
    volumes:
    - data:/home/git/data:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    env_file:
      - .env
    networks:
      network:


volumes:
  redis-data:
  postgres:
  data:

networks:
  network:
