version: '2.3'

services:
  gitlab-redis:
    restart: always
    image: redis:6.2.6
    command:
    - --loglevel warning
    volumes:
    - gitlab-redis-data:/data:Z
    networks:
      gitlab-network:
        ipv4_address: xxx.xxx.xxx.xxx


  gitlab-postgres:
    restart: always
    image: postgres:14
    volumes:
    - gitlab-postgres:/var/lib/postgresql:Z
    env_file:
      - ./.env/.gitlab-postgres-env
    networks:
      gitlab-network:
        ipv4_address: xxx.xxx.xxx.xxx


  gitlab:
    restart: always
    image: gitlab/gitlab-ce:16.7.3-ce.0
    depends_on:
    - gitlab-redis
    - gitlab-postgres
    ports:
    - "80:80"
    volumes:
    - gitlab-data:/home/git/data:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    networks:
      gitlab-network:
        ipv4_address: xxx.xxx.xxx.xxx
    env_file:
      - ./.env/.gitlab-env

volumes:
  redis-data:
  postgres:
  data:

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: xxx.xxx.xxx.xxx/xx
      options:
        com.docker.network.bridge.enable_ip_masquerade: "true"
