version: '3.7'

services:

# The 'setup' service runs a one-off script which initializes users inside
# Elasticsearch — such as 'logstash_internal' and 'kibana_system' — with the
# values of the passwords defined in the '.env' file. It also creates the
# roles required by some of these users.
#
# This task only needs to be performed once, during the *initial* startup of
# the stack. Any subsequent run will reset the passwords of existing users to
# the values defined inside the '.env' file, and the built-in roles to their
# default permissions.
#
# By default, it is excluded from the services started by 'docker compose up'
# due to the non-default profile it belongs to. To run it, either provide the
# '--profile=setup' CLI flag to Compose commands, or "up" the service by name
# such as 'docker compose up setup'.
#  setup:
#    profiles:
#      - setup
#    build:
#      context: setup/
#      args:
#        ELASTIC_VERSION: 8.11.3
#    init: true
#    volumes:
#      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
#      - ./setup/lib.sh:/lib.sh:ro,Z
#      - ./setup/roles:/roles:ro,Z
#    env_file:
#      - ./.env/.setup-env
#    networks:
#      - network
#    depends_on:
#      - elasticsearch

  
  elasticsearch:
    image: elasticsearch:8.11.3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    env_file:
      - ./.env/.elasticsearch-env
    networks:
      - network
    restart: unless-stopped

  logstash:
    image: logstash:8.11.3
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    env_file:
      - ./.env/.logstash-env
    networks:
      - network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: kibana:8.11.3
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    env_file:
      - ./.env/.kibana-env
    networks:
      - network
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  network:
    driver: bridge

volumes:
  elasticsearch:
